class Autogenerated {
  int? idIsi;
  int? idPengeluaran;
  String? kategori;
  String? namaPengeluaran;
  String? tgl;
  int? jumlah;
  String? note;
  String? buktiPic;

  Autogenerated(
      {this.idIsi,
        this.idPengeluaran,
        this.kategori,
        this.namaPengeluaran,
        this.tgl,
        this.jumlah,
        this.note,
        this.buktiPic});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    idIsi = json['id_isi'];
    idPengeluaran = json['id_pengeluaran'];
    kategori = json['kategori'];
    namaPengeluaran = json['nama_pengeluaran'];
    tgl = json['tgl'];
    jumlah = json['jumlah'];
    note = json['note'];
    buktiPic = json['bukti_pic'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id_isi'] = this.idIsi;
    data['id_pengeluaran'] = this.idPengeluaran;
    data['kategori'] = this.kategori;
    data['nama_pengeluaran'] = this.namaPengeluaran;
    data['tgl'] = this.tgl;
    data['jumlah'] = this.jumlah;
    data['note'] = this.note;
    data['bukti_pic'] = this.buktiPic;
    return data;
  }
}